### ISSUE TITLE
100 by default

### ISSUE THREAD

**Issue by DavidM1337** [klikk/supraball-serverlist#1]
I'd say make 100 per page by default. There is really no use for less. Is there?

**Comment by klikk** [comment]
I think it is 100 by default now, or do you mean completely remove all other options?

**Comment by DavidM1337** [comment]
oh, it looks different after a refresh! yeah

**Comment by DavidM1337** [comment]
indeed, the options are useless

**Comment by klikk** [comment]
I removed all other options but 100 and all ( if we will have more servers in the future )
